spring:
  application:
    name: SkinTrack
  datasource:
    url: jdbc:postgresql://35.240.139.1:5432/skintrack
    username: postgres
    password: terserah
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5000KB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajib.aiwa@gmail.com
    password: zeufmiklqwlyjejk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  key: 5i4gvIYPXXxmPXQ4zwumQSFwE6ID0ytg
  access-token-expiration: 7776000000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
